= My Glimpse Of Propositional Logic Inside The Ivory Tower Of Mathematics
The Contributors
:toc:

:numbered:
== Introduction

I'm a mathematical barbarian, but a few days ago I broke into the ivory tower of
mathematics and learnt the basics of Propositional Logic. In order to help me
learn it, I wrote this tutorial. It helped me, and perhaps you'll find it useful
too.

=== Licence

This work is licensed under a
http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons
Attribution-ShareAlike 4.0 International License].

=== Contributing

All contributions (corrections, amendments, additions etc) welcome at
https://github.com/tlocke/maths[https://github.com/tlocke/maths].


=== Formats

This book is available in the following formats:

[horizontal]
Web:: http://maths.tlocke.org.uk/
EPUB:: http://maths.tlocke.org.uk/maths.epub


== Propositions

In propositional logic, we're only interested in sentences that are either true
or false. Such sentences are known as _propositions_. Here are some sentences
together with explanations of whether they are propositions or not:

* _How many miles to Crinnis?_
+
This is a question, so not a proposition.

* _Elephants have four legs._
+
Yay, an actual proposition! It's a sentence that is either true or false.

* _Don't dilly-dally._
+
This isn't true or false, it sounds like someone admonishing somebody. Not a
proposition.

* _The capital of France is Paris._
+
Yes, a proposition.

* _He likes chocolate._
+
This sounds like a proposition, but according to those logicians in the ivory
tower it doesn't count because it relies on knowing who `he' is.

* _Don't spoil the ship for a ha'peth of tar._
+
This is a proverb, not a proposition.

I've got this nagging doubt in my mind. Most propositions I can think of aren't
_totally_ ambiguous. Take the `Elephants have four legs' example. Maybe there's
a three legged elephant in existence, perhaps one in a zoo got gangrene or
something and had to have a leg amputated... Nevertheless, let's suspend our
disbelief and imagine all those perfect propositions.

:numbered!:
=== Questions

. Which of the following are propositions?
.. Who is John Galt?
.. He's over there.
.. Three divided by three is one.
.. Belgium is a European country.
.. Praise be!
.. Blue is a colour.

. Are the following propositions true or false?
.. Four is greater than two.
.. Tennis is a colour.
.. A square has eight sides.
.. A cube has eight corners.
.. Birmingham is a city in England.
.. The word `rotavator' is a
      http://en.wiktionary.org/wiki/palindrome[palindrome].


:numbered:
== Expressions

It seems that the next thing the logicians do is string together propositions.
They call the result an _expression_. So two propositions might be:

[example]
Abelard likes coffee. +
Abelard likes cake.

And an expression formed from these propositions might be:

[example]
Abelard likes coffee and Abelard likes cake.

This expression is true if both the propositions are true, otherwise it is
false. Another expression we can make from our propositions is:

[example]
Abelard likes coffee or Abelard likes cake.

This expression is false if both propositions are false, otherwise it's true.
Those mathematicians from the Ivory Tower use the term _connectives_ for the
`and' and `or' that join propositions to make expressions.

:numbered!:
=== Questions

. Are the following expressions true or false?
.. The film Erin Brokovich stars Julia Roberts and 16 is greater than 4.
.. London is the capital of France or Paris is the capital of France.
.. Some people have brown eyes and humans lay eggs.
.. Four multiplied by two is twenty or it has never rained in Wales.
.. Toothpaste is harder than diamond and less than 100 films have ever been
   made.


:numbered:
== Labels

Rather than always writing propositions out in full, those work-shy logicians
assign a label to them. So for the expression:

[example]
Abelard likes coffee and Abelard likes cake.

the two propositions can be labelled P and Q:

[example]
P: Abelard likes coffee. +
Q: Abelard likes cake.

and the expression can be written:

[example]
P and Q

Now that we've said what P and Q stand for we write the expression:

[example]
Abelard likes coffe or Abelard likes cake.

and write it using the labels as:

[example]
P or Q

:numbered!:
=== Questions

. For the following expressions, assign labels to the propositions and write the
  expression using the labels.
.. The film Erin Brokovich stars Julia Roberts and 16 is greater than 4.
.. London is the capital of France or Paris is the capital of France.
.. Some people have brown eyes and humans lay eggs.
.. Four multiplied by two is twenty or it has never rained in Wales.
.. Toothpaste is harder than diamond and less than 100 films have ever been
   made.

== Rosetta Stone

* Expression - Formula, Compound Proposition

:numbered!:
[appendix]
== Answers To Section Questions

=== <<_propositions>>

. {empty}
.. Not a proposition.
.. Not a proposition.
.. A proposition.
.. A proposition.
.. Not a proposition.
.. A proposition.
. {empty}
.. True.
.. False.
.. False.
.. True.
.. True.
.. True.

=== <<_expressions>>

. {empty}
.. True.
.. True.
.. False.
.. False.
.. False.

=== <<_labels>>

. {empty}
.. P: The film Erin Brokovich stars Julia Roberts. +
   Q: 16 is greater than 4. +
   P and Q
.. A: London is the capital of France. +
   B: Paris is the capital of France. +
   A or B
.. P: Some people have brown eyes. +
   Q: Humans lay eggs. +
   P and Q
.. P: Four multiplied by two is twenty. +
   Q: It has never rained in Wales. +
   P or Q
.. P: Toothpaste is harder than diamond. +
   Q: Less than 100 films have ever been made. +
   P and Q
